apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}